n_frames: -1

dataset:
  depth_scale: 1000 
  image_stride: 1 
  depth_min_th: 0.4
  depth_max_th: 1.0

mapping:
  max_points_per_voxel: 2

alignment:
  stable_features_min_th: 0.0
  stable_features_max_th: 1.2

image_matcher:
  matching_frequency: 1
  matching_distance_th: 0.5
  imgs_height: 220
  imgs_width: 260
  #TODO: fix this path in some way
  superpoint_weights_path: "weights/superpunto.pth" 
  non_maximum_suppression: 8
  confidence_th: 0.015
  nn_th: 0.7
  homography_confidence_th: 30

deformation:
  graph_consistency_weight: 10.0
  deformation_weight: 10.0
  max_num_iterations: 100

