width: 640
height: 480
intrinsics:
- - 517.3 # fx
  - 0.0
  - 318.6 # cx
- - 0.0
  - 516.5 # fy
  - 255.3 # cy
- - 0.0
  - 0.0
  - 1.0
extrinsics:
- - 0.0 # tx
  - 0.0 # ty
  - 0.0 # tz
- - 0.0 # qx
  - 0.0 # qy
  - 0.0 # qz
  - 1.0 # qw
